version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "9906"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: maildev/maildev
    ports: ["1025", "1080"]
    network: php
###< symfony/mailer ###
