version: '3.7'
services:
    gestion-travaux-api:
        container_name: gestion-travaux-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - gestion-travaux-database
        image: php:8.3-apache
        volumes:
            # - ./docker/php.ini:/usr/local/etc/php/php.ini
            - ../gestion-travaux-api:/var/www/
        ports:
            - "8001:80"
        networks:
            - php

    gestion-travaux-database:
        image: mysql:latest
        container_name: database_gestion_travaux
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: gestion_travaux
            MYSQL_ROOT_PASSWORD: password
        networks:
            - php
        ports:
            - "9906:3306"

    phpmyadmin:
        container_name: phpmyadmin_gestion_travaux
        depends_on:
            - gestion-travaux-database
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: gestion-travaux-database
        networks:
            - php

networks:
    php:

volumes:
    dbdata:
        driver: local
