version: '3.7'
services:
    gestion-travaux-api:
        container_name: gestion-travaux-api
        build:
            context: .
            dockerfile: ./php/Dockerfile
        depends_on:
            - database
        image: php:8.2-apache
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini-development
            - ../gestion-travaux-api:/var/www/
        ports:
            - 5000:8000
        links:
            - database:database
        networks:
            - php

    database:
        image: 'mysql:latest'
        container_name: database_gestion_travaux
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: gestion_travaux
            MYSQL_ROOT_PASSWORD: password
        networks:
            - mysql-phpmyadmin
            - php
        ports:
            - "9906:3306"
            # - '3306'

    # phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin_gestion_travaux
        depends_on:
            - database
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
            # - "8020:80"
        environment:
            PMA_HOST: database
        networks:
            - mysql-phpmyadmin


networks:
    local:
    mysql-phpmyadmin:
    php:

volumes:
    dbdata:
        driver: local
