version: '3'

services:
###> doctrine/doctrine-bundle ###
  gestion-travaux-api:
    ports:
     - 8000:8000
  database:
    ports:
      - "9906"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: maildev/maildev
    ports: ["1025", "1080"]
###< symfony/mailer ###
