name: Codeception tests

on:
    pull_request:
        branches: [dev]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-versions: ['8.3']

        services:
            mysql:
                image: mysql:8.4
                env:
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
                ports:
                    - 3306:3306

        steps:
            - uses: actions/checkout@v4
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

            - name: Setup dependencies
              uses: ./.github/actions/set-dependencies
              with:
                mysql_database: ${{ secrets.MYSQL_DATABASE }}
                mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

            - name: Install dependencie with yarn
              run: yarn

            - name: Install symfony CLI
              run: |
                  curl -sS https://get.symfony.com/cli/installer | bash
                  mv ~/.symfony*/bin/symfony /usr/local/bin/symfony

            - name: Install JWT keys
              run: php bin/console lexik:jwt:generate-keypair

            - name: Run tests
              run: yarn test && yarn replace-env
